export const STATE_TO_TRUE = "true";
export const STATE_TO_FALSE = "false";
export const INACTIVE_STATE = "inactive"
export const ACTIVE_STATE = "active"
export const DEFAULT_ORIENTATION = "horizontal";
export const VERTICAL_ORIENTATION = "vertical";
export const TRANSFORM_DURATION = 600;
export const TRANSFORM_EASING = "cubic-bezier(.48,1.55,.28,1)";
export const DEFAULT_INDICATOR = { className: "", transformDuration: 0, transformEasing: "" }